name: Build Every Commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CI_LLVM_VERSION: "18.1.1"

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      - name: Build LLVM
        shell: cmd
        run: |
          git clone --config core.autocrlf=false -b llvmorg-${{ env.CI_LLVM_VERSION }} --depth 1 https://github.com/llvm/llvm-project.git
          mkdir llvm-build
          cd llvm-build
          cmake ..\llvm-project\llvm -Thost=x64 -DLLVM_TARGETS_TO_BUILD="X86;AArch64;ARM;WebAssembly" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DBUILD_SHARED_LIBS=OFF -DCMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_ENABLE_ZSTD=OFF
          cmake --build . --config Release
          cmake "-DCMAKE_INSTALL_PREFIX=..\llvm" -P cmake_install.cmake
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm_witharm_${{github.sha}}
          path: llvm/bin/LLVM-C.dll
