name: Build Every Commit

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-windows-x64:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    repository: konovod/monocypher.cr
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                    md .build
                    cd ext
                    cl /LD /O2 /MT monocypher.c monocypher-ed25519.c
                    cd
                    dir
            -   name: Upload Artifact
                uses: actions/upload-artifact@v2
                with:
                    name: monocypher_${{github.sha}}
                    path: .build/*.dll
            -   name: Upload Artifact2
                uses: actions/upload-artifact@v2
                with:
                    name: monocypher_${{github.sha}}
                    path: .build/*.lib
