name: Build Every Commit

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-windows-x64:
        runs-on: windows-latest
        steps:
            - name: get fft
              run: |
                  iwr https://gamedev.ru/files/?id=159585 -OutFile dbc_fft.zip
                  7z x dbc_fft.zip
            - name: Build
              shell: cmd
              run: |
                call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                cd release
                cl /O2 /MT check.cpp
                dir
                check.exe
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: fft_${{github.sha}}
                path: release/*.exe
